### ISSUE TITLE
Notes after a test run

### ISSUE THREAD

**Issue by luprchal** [castles/OSCWebMixer2#1]
Hi Marc,

first of all - great job done!!! The app is a miracle! We tested with six singers over two full-day rehearsals and they loved it! Had also two iPads connected and a laptop with Ableton Live, sending commands to the SD9. Nice thing is that we have OTH OSC commands punched in the ABL session and they worked along the iPad command-set, as we have both loaded in the console. So the console seems to accept multiple command-sets at a time.

The admin section is pretty intuitive, although a few minor touches would be nice:
- a hint to add a **DiGiCo iPad** external device to the console, not OTH OSC ... that took me like 30mins to realize :-D
- be a little more specific about receive and send ports, eg. "console's send"; these binary things always give me a headache
- add channel numbers to the channel section

We've also had a few issues, my notes from the rehearsal:

**Error connecting new web client**
console log:

> New Connection
> /home/admin/oscwebmixer2/OSCWebMixer2/index.js:133
> 					order: config.channels[i].order,
> 					                          ^
> 
> TypeError: Cannot read properties of undefined (reading 'order')
>     at buildConfig (/home/admin/oscwebmixer2/OSCWebMixer2/index.js:133:32)
>     at WebSocketServer.<anonymous> (/home/admin/oscwebmixer2/OSCWebMixer2/index.js:192:15)
>     at WebSocketServer.emit (node:events:517:28)
>     at WebSocketServer.completeUpgrade (/home/admin/oscwebmixer2/OSCWebMixer2/node_modules/ws/lib/websocket-server.js:431:5)
>     at WebSocketServer.handleUpgrade (/home/admin/oscwebmixer2/OSCWebMixer2/node_modules/ws/lib/websocket-server.js:339:10)
>     at Server.upgrade (/home/admin/oscwebmixer2/OSCWebMixer2/node_modules/ws/lib/websocket-server.js:114:16)
>     at Server.emit (node:events:517:28)
>     at onParserExecuteCommon (node:_http_server:931:14)
>     at onParserExecute (node:_http_server:825:3)
> 
> Node.js v18.19.0

Note: 

1. Config of the digico **session has changed during runtime - channels added**.
2. Order of channels in the admin section was changed before adding new channels to console.

**Webapp gets disconnected, but does not notify the user** 
- Probably only when app saved as a desktop app, it seemed to work correctly in a common browser - Safari, Chrome
- Tested on iPhone and Android

**And finally a handful of "nice-to-have" feature suggestions:**

- logarithmic scale on app faders, now they seem to be linear
- name of current snapshot in client app header
    - I have added that as a plugin, but changes to mixer.js obviously needed to be done too
    - After receiving “/Snapshots/Current_Snapshot” save snapshot number to a global var and send “/Snapshots/names/?” to receive the whole list; pick the correct number, get args[3] (snap name) and send an arbitrary msg to the clients to update the <snap>.innerHTML
- (Low priority) add an aux output level meter to the client app

Thanks a lot for all the great work, we will definitely send a contribution! 
Regards, Lukas

**Comment by castles** [comment]
Hi Lukas. Great. I'm glad you managed to get it to work!

I used the system over the weekend as well and noticed the faders were linear as well. I actually released an update for this yesterday, so if you get the latest version this should be much better.

I would like to see an aux output level meter in the client app but I'm not sure if DiGiCo expose this data over OSC. Have you seen any metering in the DiGiCo iOS app? 

Thanks for the other feedback. I will work on these when I can.

**Comment by luprchal** [comment]
Yes, the console sends it - "/Meters/...". I actually had to block these from the console to be able to read something useful.
The iPad app also request session filename every 5 seconds or so. A bit annoying.. :)

**Comment by castles** [comment]
Oh, that is interesting. I didn't notice the /Meters but it could have something to do with my setup. The SD9 I'm using doesn't have Stealth Core 2 so that might be the difference. Do you have stealth core 2?

The session filename is annoying. Seems strange that it has to ask so often. I could probably cache the value so that we don't have to broadcast it to everything that is connected.

I haven't been able to replicate the issue with the webapp ui not updating when its disconnected. Do you have any more details about this issue?

Where in the interface were you displaying the snapshot to the user? I'm thinking the best spot would be at the top just under the toolbar but I haven't tried it yet.

**Comment by luprchal** [comment]
Yes, it's core 2.

The issue only happened in the "desktop app". I guess it uses some simplified browser core and it does not handle ws correctly. No problem in a "normal" browser window.

I added a <div> directly to the body so it showed at the bottom by default. Was lazy to fiddle with CSS more... But I agree - best spot would be below the AUX selection.

**Comment by castles** [comment]
Thanks.

How are you creating the desktop app? Are you on windows or mac?

I discovered today that the metering shows up if you are on the mix tab of the iPad. I should be able to get the metering working. 

I released a small update today with some fixes for your other items.

**Comment by castles** [comment]
Hey @luprchal, I just released a new version of webmixer that displays the current snapshot. Please have a play with it and let me know what you think.

**Comment by castles** [comment]
I'm closing this issue as I believe its all sorted
