### ISSUE TITLE
Unsure how to connect

### ISSUE THREAD

**Issue by 4IceFire** [castles/OSCWebMixer2#2]
Hi there, this program looks amazing and would be incredibly useful for our church!
I am unable to make it work though sadly. We use an iPad already which normally connects to our SD9 desk with no problems. But I can't seem to get the OSC Web Mixer to connect. I've inputted the correct IP and ports from what I believe is correct, but it doesn't seem to be connecting. The terminal starts off by just requesting to the sound desk, but then eventually it says "message received over UDP", but nothing really changes.

I'm not sure as to how to problem solve this so any help would be greatly appreciated!

![Screen Shot 2024-09-29 at 11 19 43 am](https://github.com/user-attachments/assets/625de502-a80e-4b7a-b077-94dfc864f333)
![IMG_9017](https://github.com/user-attachments/assets/19442b3a-bd59-4d69-915b-f0505b489800)

![Screen Shot 2024-09-27 at 4 43 19 pm](https://github.com/user-attachments/assets/46d6a259-db19-4622-938b-c1065bf39dd0)

**Comment by castles** [comment]
Have you tried your ports around the other way?

**Comment by IceFire4** [comment]
I have not. I'll give that a go. Are there any recommended ports to use?

**Comment by castles** [comment]
I always found the iPad ports confusing so that’s why I reversed it in webmixer. Maybe I should have kept it the same for consistency. 

I don’t think there are any digico recommended ports. You just want to make sure you don’t clash with any other ports that are in use.

**Comment by 4IceFire** [comment]
Changing the ports has made it work! Thank you!

**Comment by castles** [comment]
Awesome
